site_name: Self Employed Indian
theme:
    name: null
    custom_dir: 'docs/custom_theme2/'
    sidebars: 
        - about
        - search
extra:
    logo: files/self_employed_indian.png
    sidebars:
        - about
        - navigation
    homepage_sidebars:
        - about
        - navigation

nav:
    - Thoughts:
        - Should you be self employed: 'should_you_be_self_employed'
    - Stack:
        - Zoho invoice: 'stack/zoho_invoice'
    - How to: 
        - Create recurring invoice: 'how_to/create_recurring_invoice_zoho_invoice'



markdown_extensions:
  - toc:
      permalink: true
